### ISSUE TITLE
Repository name does not follow convention

### ISSUE THREAD

**Issue by danmarsden** [mynaparrot/moodle-mod_plugnmeet#1]
Your repository name should use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "mod_attendance" the correct name to use would be: "moodle-mod_attendance"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top.

**Comment by jibon57** [comment]
Thanks for the review. We've changed it. New link: https://github.com/mynaparrot/moodle-mod_plugnmeet
