### ISSUE TITLE
missing capability checks in external classes

### ISSUE THREAD

**Issue by danmarsden** [mynaparrot/moodle-mod_plugnmeet#11]
Functions like mod_plugnmeet_create_room, delete_recording, get_recordings do not check if the current logged in user should be able to perform the action - this means that anyone can create a room (and enter as admin), anyone can delete any room, anyone logged in can obtain the recordings for any room etc etc.

Each external_api function should contain a capability check - can this user perform this task within this course etc.- ensuring that an activity inside a course is only available to it's enrolled users, ensuring that only appropriate users with elevated permissions can create a room/delete a room etc etc.

**Comment by danmarsden** [comment]
I note you have listed some capabilities in the services.php file - but these are informational only - you need to actually physically check those capabilities inside your external functions themselves.

**Comment by jibon57** [comment]
Thank you for pointing this.
