### ISSUE TITLE
Exception - syntax error, unexpected ')' 

### ISSUE THREAD

**Issue by YndOr** [mynaparrot/moodle-mod_plugnmeet#14]
So I tried to install this plugin and unfortunately got this error message.

Exception - syntax error, unexpected ')' 

My Moodle version is 3.7

**Comment by jibon57** [comment]
Currently support moodle 3.11+ only

**Comment by YndOr** [comment]
Hi,

Thanks for the respond. May I ask what LTI means?

**Comment by jibon57** [comment]
You can read more from here: 
https://docs.moodle.org/310/en/LTI_and_Moodle
https://www.plugnmeet.org/docs/user-guide/lti
