### ISSUE TITLE
Activity forcefully goes in the gradebook.

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/moodle-mod_plugnmeet#15]
When one chooses Settings-Grade-None, the activity is still present in the gradebook showing default points. This is not convenient when say a teacher wants to have it only as a connection channel for online classes and does not want it in the gradebook.

**Comment by vitaliybaran** [comment]
This bug also prevents a course from being completed because the activity stays in the gradebook.

**Comment by jibon57** [comment]
You can try this: https://moodle.org/mod/forum/discuss.php?d=413714
By default activity will be listed in grade book.
