### ISSUE TITLE
Uploaded Background image is shadowed

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/moodle-mod_plugnmeet#16]
After the latest update of Moodle plugin, the custom background image is greatly shadowed. So when the waiting room is activated, the students see something like this: 
[https://drive.google.com/file/d/1lgyQiql05flCgspBAzpviP68HLoPgDrQ/view?usp=sharing]

However, the original color of the image is light sepia.

The original background images works fine though.

**Comment by jibon57** [comment]
@vitaliybaran are you using demo server? If so then you can try again now. We tried to solve it in this pull: https://github.com/mynaparrot/plugNmeet-client/pull/187 .. If you still face problem then please send me that background image here.
