### ISSUE TITLE
Screen calibration problem with camera on the side

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/moodle-mod_plugnmeet#17]
This problem was already solved once, but now it's back.
When the whiteboard is launched and the video goes to the side panel, there seems to be something wrong with screen calibration on a large monitor. You start writing on the whiteboard and the actual scribblings appear some distance to the right of your pointer. Minimizing and then maximizing video or the whole screen helps to resolve this issue, but it is still very annoying to have to do that. Everything works fine on an ordinary laptop (on a smaller screen).

**Comment by jibon57** [comment]
@vitaliybaran can you try again now?

**Comment by vitaliybaran** [comment]
Yes, it works perfectly fine now.

**One more thing:** Before the latest changes it was possible to switch between the whiteboard and the external media player, but now when the media player starts, the whiteboard is dead. It is important, I think, to have this option back for the teacher because if, say, the teacher presents a pdf file on the board with a listening comprehension task, it is vital that the students could see the whiteboard and listen to the audio file at the same time. Is it possible to have this option back? Or maybe it is possible have the media player minimized somewhere at the bottom of the page under the board so that the teacher could have control of both the whiteboard and the media player?

P.S. when I try to share an audio file thru screen demonstration, there is echo even when all the parties use headphones. Is it only my case or some bug?

**Comment by jibon57** [comment]
@vitaliybaran thanks for the idea. The only problem here is with smaller devices like mobile. It's being hard to show both elements side by side but we'll think about it.
In future for this type discussion please write here: https://github.com/mynaparrot/plugNmeet-server/discussions
It's easier to track.

**Comment by vitaliybaran** [comment]
One last thing:
as to the mobile version, it is not necessary to have this option on a phone as it is not convenient for the teacher to conduct a lesson on a phone, at least I think so. It's enough to make it possible for the student to be able to listen to the recoding played by the teacher while viewing the whiteboard on the phone.

**Comment by jibon57** [comment]
@vitaliybaran can you try again now? We've tried to improve it here: https://github.com/mynaparrot/plugNmeet-client/pull/244

**Comment by vitaliybaran** [comment]
thanks. now I can control both the whiteboard and the media player.

**Comment by jibon57** [comment]
@vitaliybaran thanks for confirmation.

I think you've written in moodle that you want to translate the interface in `Ukrainian` language. If you want then you can do it from here: https://crowdin.com/project/plugnmeet-client . After you'll finish then we'll merge into main project.

**Comment by vitaliybaran** [comment]
I've started translating. I also detected some mistakes in the English version.

**Comment by vitaliybaran** [comment]
Finished translation

**Comment by vitaliybaran** [comment]
I have just modified translation of some strings.
