### ISSUE TITLE
The plugin stopped working

### ISSUE THREAD

**Issue by vitaliybaran** [mynaparrot/moodle-mod_plugnmeet#18]
The plugin stopped working on my site. My Moodle is not in the root folder. When I press "Join" button, nothing happens and the site becomes dead. The site also becomes dead once the activity page is entered - once you're there, you're trapped. What could it be? Is it only on my site or elsewhere?

**Comment by jibon57** [comment]
I think you're using demo server. Sometime it got problem because of heavy load. Consider to setup your own server: https://www.plugnmeet.org/docs/installation

**Comment by vitaliybaran** [comment]
Thanks for the answer. 
I am sorry to say that, but think I'll have to give up on the plugin (I still think it's perfect for teaching) as I am not an IT specialist and I don't understand 95% of the installation instructions for setting up my own server (LOL). I have a shared hosting of my Moodle site, however, I simply won't be able to follow these instructions since I just don't understand my way about it.

**Comment by jibon57** [comment]
Please send email to bob[@]mynaparrot.com . @wbobteng will help you
