### ISSUE TITLE
No recording button after update to 1.2.0 (2022111300)

### ISSUE THREAD

**Issue by efakhimi** [mynaparrot/moodle-mod_plugnmeet#20]
Hey Guys,
I was using 1.0.3 (2022051200) version and moodle v4 and everything was fine but after I updated plugin yesterday there was 2 issues which I have find solution for first which I will explain for people how have less technical skill, but I am busy right now on other project and I wish somebody can help me solving this.

issue 1) all the recorded meeting were not showing after update 
solution : simply go to the activity setting and push update button, no need to change anything, there is a minor changes in other feature items which causes this problem.
I have find the solution by looking at /views/recordings_part.php

issue 2) there is no recording button when you are joining the conference, everything is fine when I am testing the plugnmeet server by going to login.html and using api and api secret. on other feature options I set every thing on yes except auto cloud recording.
first I guessed maybe it is because admin is detecting as normal user but it has other administration options except recording.
I installed plugnmeet-recorder and was working on previous version and service is running when I check the status.

Please help me find answer for issue 2. 

Thanks in advance.

**Comment by jibon57** [comment]
For your issue 2, make sure that you've updated your server as well as. If you're using local client then make sure you've updated it from plugin setting or use remote. 

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/6080277/203219199-594a8c62-9216-4046-8d0e-0d42007ddd5c.png">
