### ISSUE TITLE
Field "grade" does not exist in table "plugnmeet"

### ISSUE THREAD

**Issue by caiadogithub** [mynaparrot/moodle-mod_plugnmeet#21]
Hi,

When accessing the page ".../grade/edit/scale/index.php" I got this error message:

"...

Field "grade" does not exist in table "plugnmeet"

[More information about this error](http://docs.moodle.org/401/pt_br/error/moodle/ddlfieldnotexist)
Debug info:
Error code: ddlfieldnotexist
Stack trace:

    line 680 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1978 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 186 of /mod/plugnmeet/lib.php: call to moodle_database->record_exists()
    line 368 of /lib/grade/grade_scale.php: call to plugnmeet_scale_used_anywhere()
    line 152 of /grade/edit/scale/index.php: call to grade_scale->is_used()

..."

Ricardo

**Comment by jibon57** [comment]
You can try to download zip file from main branch.

**Comment by caiadogithub** [comment]
The code from the main branch = my Moodle site (1.2.0 2022111300)
