### ISSUE TITLE
missing thirdpartylibs.xml 

### ISSUE THREAD

**Issue by danmarsden** [mynaparrot/moodle-mod_plugnmeet#5]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by jibon57** [comment]
https://github.com/mynaparrot/moodle-mod_plugnmeet/commit/b62386028e68026d1062b860c1df05cdaac34c0e
